### ISSUE TITLE
Config option to disable checking if file exists which could sometimes fail though file exists

### ISSUE THREAD

**Issue by Pradhyo** [gcalmettes/reveal.js-d3#10]
I was having issues loading external html file due to the [doesFileExist()](https://github.com/gcalmettes/reveal.js-d3/blob/master/reveald3.js#L277) when I tried to open the main html file directly

```
      <section class="fig-container" data-file="index1.html">
      </section>
```

I was able to workaround this by always returning `resolve(true)` but what do you think about a config option to disable this function?

**Comment by gcalmettes** [comment]
Hi @Pradhyo, 
I added a new `disableCheckFile` option (see [configuration options](https://github.com/gcalmettes/reveal.js-d3#configuration) set to `false` by default.

Associated commit 2de2e9c6951971a004dcde90904a4d504afdbaef

Note that I also switched from `xmlHttpRequest` to the new `fetch` api for the `doesFileExist` function, in case the problem was coming from this.

**Comment by Pradhyo** [comment]
Thank you so much
