### ISSUE TITLE
Get out of full iframe slide after interaction

### ISSUE THREAD

**Issue by nbremer** [gcalmettes/reveal.js-d3#14]
On the example slide that shows the full iframe, I can click inside of it, interact with it, and still my front and back arrows go to the next slide. However, this isn't working for my local version (and it's also not working when I load the demo from this repo and interact with the local version). Once I click inside the iframe, my keydown's aren't making the slide change. Any idea what the difference might be, how I can interact but still move to the next slide? 

I do get a warning of `Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.`, even though the iframe still loads. Although I'm guessing that isn't the issue

**Comment by gcalmettes** [comment]
This sounds like a problem of the propagation of the key presses to the parent.

Are you loading a local content (e.g.: local contained .html with all the code in it) or are you linking to a deployed content (e.g: example deployed on bl.ocks or other)?

**Comment by nbremer** [comment]
Ah, I was indeed loading deployed content. I tried switching to my local one, and then I can indeed click inside of the visual, and still my keypresses are registered.

However, I don't have the local version of all the content that I'm intending to show (full screen), but I would prefer to hold the presentation from my local server. Although not a fix, I've now set an extra `data-iframe` attribute on this particular section. Then added a function that checks if the current slide holds that attribute, and if yes, set `Reveal.configure({ controls: true })`, otherwise to `false`, which shows the controls in the bottom right (you can make them smaller by setting the `font-size` CSS setting smaller), which do remain clickable, even after having interacted with the background page :)

**Comment by gcalmettes** [comment]
Yes, indeed, I had encountered this problem too at one point when trying to interact with deployed content.

The problem comes from the [Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) (not to be confused with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)) which prevents the plugin to add an `eventListener` on the iFrame content window to propagate back to the parent the key presses event. At least only this stepped is prevented, and the content is still loaded ;)
I tried to implement a workaround to the same-origin-policy by setting up a communication system between the Reveal content and the iFrame content using [window.postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), but this forces you to modify the code of the deployed visualization, which is not always possible, so I had killed the idea.

My current workaround to this problem is to add an invisible div at the top right corner of the slide (and in front of the iFrame), so that I can "escape" from the iFrame content and come back to the Reveal presentation by clicking on this div element.
This is basically along the same idea than what you're doing by making the controls appear, except that you can control the visibility (opacity) of your div et make it the size you want to make sure not to miss it when you click.

**Comment by nbremer** [comment]
Ah yes, that makes sense indeed.

And good workaround! ^_^

**Comment by gcalmettes** [comment]
Writing this here as documentation of a workaround to the ` Same-origin policy` problem:

A workaround to this problem is to add an event listener at the end of the Reveal.js configuration so that the `arrow controls` appear on specific slides.

```
Reveal.addEventListener('slidechanged', function (event) {
    if (event.currentSlide.hasAttribute('my-special-attribute') {
        // make the controls to appear
        document.querySelector('aside.controls').style.display = 'block'
    } else {
         // remove the controls
        document.querySelector('aside.controls').style.display = 'none'
    }//else
 })
```

**Comment by gcalmettes** [comment]
Writing this here as documentation of a workaround to the ` Same-origin policy` problem:

A workaround to this problem is to add an event listener at the end of the Reveal.js configuration so that the `arrow controls` appear on specific slides.

```
Reveal.addEventListener('slidechanged', function (event) {
    if (event.currentSlide.hasAttribute('my-special-attribute') {
        // make the controls to appear
        document.querySelector('aside.controls').style.display = 'block'
    } else {
         // remove the controls
        document.querySelector('aside.controls').style.display = 'none'
    }//else
 })
```
