### ISSUE TITLE
A "slide-background-content" div is blocking my visual

### ISSUE THREAD

**Issue by nbremer** [gcalmettes/reveal.js-d3#15]
Every iframe that gets added to the background (whether from a local file, or a url), is hidden by revealJS' `slide-background-content` div. See the image below:

<img width="630" alt="extra_div_screenshot" src="https://user-images.githubusercontent.com/5062746/56846676-46196100-68d2-11e9-95de-55b1c35170a1.png">

This is preventing me from interacting with the visual behind it, because each `.reveal .slide-background-content` is set to be 100% in `width` and `height`. I've been using a `slidechanged` event listener to remove this element from the background that has `present` set (and only when needed), but this extra div does not seem to be in place in the demo online. 

I was therefore wondering what might be causing this for my version. Could it be due to the difference in revealJS versions? I'm using 3.8.0, whereas the demo is based on 3.5.0? (it seems some things have been changed, for example, there's no more `head.min.js` or `classList.js` file?

**Comment by gcalmettes** [comment]
Ha, I haven't tested it with the latest Reveal.js version. Let me look into that.

**Comment by gcalmettes** [comment]
That was indeed due to a change in how Reveal.js was creating the background slide.
I have now added a check to see if the new `slide-background-content` div is present, and if so the iframe will now be inserted in front of it (see [here](https://github.com/gcalmettes/reveal.js-d3/commit/573c9e448b218d1bad0f93fe1fa75591cd8b978b#diff-f7b3fb9b86eb5b20ea1d9ab683bd7b91L337))

The demo is now running on the latest version of Reveal.js.

Thanks for the report!

**Comment by nbremer** [comment]
Great! Thank you for the fix, it is now also working for me ^_^
