### ISSUE TITLE
Run "fragment" on slide change

### ISSUE THREAD

**Issue by nbremer** [gcalmettes/reveal.js-d3#20]
A feature request: With the addition of the `viewDistance`, which is great, I now run into the "issue" that some of my visuals "start their animation" before I get to the page. I'd love it if there was some sort of `-1` or `0` (whatever you want to call it) transition state that runs on the `slidechange` event :) (going forward only I guess)

**Comment by gcalmettes** [comment]
This feature request is now implemented (634fbfe19e0f8cde13af66d9a4c86f79a2d7950c)!

Adding a transition and giving it a string as index will (e.g.: `"start"`, `"onSlideChange"`, etc ...) will be considered as a `slidechange` transition (in the forward direction only) and will be triggered when the slide comes into view. 

Note that 
- (1) there is now a new option for the plugin called `onSlideChangedDelay` (default: 0) that defines the delay (in ms) with which this specific transition will be triggered after the slide change. See the demo deck for an example of the feature.
- (2) because this transition is not considered an "in slide" transition, it will never be triggered if you go backward (it is disconnected to the `fragment` system).
